package org.blank.projectmanagementsystem.domain.Enum;

public enum ArchitectureType {
    IDE,
    FRAMEWORK,
    LIBRARY,
    PROGRAMMING_LANGUAGE,
    SCRIPT_LANGUAGE,
    MARKUP_LANGUAGE,
    DATABASE,
    VCS,
    API,
    TESTING,
    DATA_STRUCTURE,
    ALGORITHM,
    DESIGN_PATTERN,
    CLOUD_COMPUTING,
    CONTINUOUS_INTEGRATION,
    CONTINUOUS_DEPLOYMENT,
    CONTINUOUS_DELIVERY,
    OTHER
}
